// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cantina_senac.Migrations
{
    [DbContext(typeof(CantinaSenacContext))]
    [Migration("20250910234214_CriacaoDatabase")]
    partial class CriacaoDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CantinaSenac.View.Postagem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("DataPublicacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Postagem");

                    b.HasDiscriminator().HasValue("Postagem");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("CantinaSenac.View.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Foto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NomeDoUsuario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Usuario");

                    b.HasDiscriminator().HasValue("Usuario");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("CantinaSenac.View.Comentario", b =>
                {
                    b.HasBaseType("CantinaSenac.View.Postagem");

                    b.Property<string>("PostagemId")
                        .HasColumnType("varchar(255)");

                    b.HasIndex("PostagemId");

                    b.HasDiscriminator().HasValue("Comentario");
                });

            modelBuilder.Entity("CantinaSenac.View.Aluno", b =>
                {
                    b.HasBaseType("CantinaSenac.View.Usuario");

                    b.HasDiscriminator().HasValue("Aluno");
                });

            modelBuilder.Entity("CantinaSenac.View.Postagem", b =>
                {
                    b.HasOne("CantinaSenac.View.Usuario", "Usuario")
                        .WithMany("Postagens")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CantinaSenac.View.Comentario", b =>
                {
                    b.HasOne("CantinaSenac.View.Postagem", null)
                        .WithMany("Comentarios")
                        .HasForeignKey("PostagemId");
                });

            modelBuilder.Entity("CantinaSenac.View.Postagem", b =>
                {
                    b.Navigation("Comentarios");
                });

            modelBuilder.Entity("CantinaSenac.View.Usuario", b =>
                {
                    b.Navigation("Postagens");
                });
#pragma warning restore 612, 618
        }
    }
}
